// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_Cd9WGmtiIx_8dysRRn_2jc918JJq-1w',
    appId: '1:199898293030:web:afde6f5073df2ffa6017e7',
    messagingSenderId: '199898293030',
    projectId: 'edufarewell',
    authDomain: 'edufarewell.firebaseapp.com',
    storageBucket: 'edufarewell.appspot.com',
    measurementId: 'G-F76DWW564M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMsDACdFfT9h7ZEhwWwy7AVAueW_1GcXM',
    appId: '1:199898293030:android:6fbbac91753da77d6017e7',
    messagingSenderId: '199898293030',
    projectId: 'edufarewell',
    storageBucket: 'edufarewell.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZEwmPjX2lZ6mITwAN59rS__syeL1bmg0',
    appId: '1:199898293030:ios:10ebb17e264eb57e6017e7',
    messagingSenderId: '199898293030',
    projectId: 'edufarewell',
    storageBucket: 'edufarewell.appspot.com',
    iosBundleId: 'com.example.clc',
  );
}
